[package]
name = "sonus"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.19.0", features = ["jpeg"]}
bevy-inspector-egui = "0.37.0"
hound = "3.5.1"
rodio = { version = "0.22.2", default-features = false, features = ["wav"] }
ringbuf = "0.5.0"
bevy_skein = "0.6.0"

[profile.dev.package."*"]
opt-level = 3
